POST http://localhost:9090/register HTTP/1.1
content-Type: application/json

{
    "username" :"Ishu",
    "password": "123",
    "email": "ishu123@gmail.com",
    "name" : "Ishika Mishra"
}


###

POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
    "email": "ishu123@gmail.com",
    "password": "123"
}



###

POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
    "email": "minakshi123@gmail.com",
    "password": "Akash1123"
}


###
GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
    "token":"73a29e8fa48234f2ce9ed9e719ea90db16a094c068fc4fd494dc675328e591a4"
}



###
POST http://localhost:9090/update_profile_data
Content-Type: application/json

{
    "token": "bc7ffc5c3b0bb4edb42c1695b5ebb231c0c85f16c6af75a239975f6dafb0e68b",
    "bio": "Your bio text here",
    "currentPost": "CTO",
    "pastWork":[
        {
            "company": "Google",
            "position": "CTO",
            "years": "3+"
        }
    ],
        "education":[
            {
                "school": "IIT",
                "degree": "B.Tech",
                "fileOfStudy": "2015-2019"
            }
        ]
    
}







###
GET http://localhost:9090/user/get_all_users
