POST http://localhost:9090/register HTTP/1.1
content-Type: application/json

{
    "username" :"mishraji",
    "password": "Akash1123",
    "email": "minakshi123@gmail.com",
    "name" : "Hum na Bataye to"
}




###

POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
    "email": "minakshi123@gmail.com",
    "password": "Akash1123"
}

###
GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
    "token":"57d665821f4a2a22b8339f73dc6cf23af8230eac10cf67ff65222d3eb1d16205"
}